language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
install:
  - pip install --upgrade six
  - pip install .
#  - pip install -r requirements/requirements-dev.txt
#  - pip install -r requirements/requirements-test.txt

script: pytest

#script: pytest --cov=peppy
#after_success:
#  - coveralls

branches:
  only:
    - dev
    - master

