site_name: Logmuse
site_url: http://code.databio.org/logmuse/
repo_url: http://github.com/databio/logmuse
pypi_name: logmuse

nav:
  - Introduction:
    - Home: README.md
    - Interactive logmuse: interactive.md
  - Reference:
    - API: autodoc_build/logmuse.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      autodoc_package: "logmuse"
      no_top_level: true
  - search

